#spring.application.name=springStudents
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: 9kLX#qhg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    show-sql: true
